#!/bin/sh

### BEGIN INIT INFO
# Provides:          xwp 
# Required-Start:    $local_fs $remote_fs $network 
# Required-Stop:     $local_fs $remote_fs $network 
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the xwp web server
# Description:       starts xwp using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/xwp/sbin/xwp
NAME=xwp
DESC=xwp
DAEMON_OPTS="-l /usr/local/xwp/conf/zlog.conf -c /usr/local/xwp/conf/xwp.xml"

# Include xwp defaults if available
#if [ -f /etc/default/xwp ]; then
#	. /etc/default/xwp
#fi

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

test_xwp_config() {
#	if $DAEMON -t $DAEMON_OPTS >/dev/null 2>&1; then
#		return 0
#	else
#		$DAEMON -t $DAEMON_OPTS
#		return $?
#	fi
	return 1
}

case "$1" in
	start)
		echo -n "Starting $DESC: "
		#test_xwp_config
		# Check if the ULIMIT is set in /etc/default/xwp
		if [ -n "$ULIMIT" ]; then
			# Set the ulimits
			ulimit $ULIMIT
		fi
		start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON || true
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --quiet --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON || true
		sleep 1
		test_xwp_config
		start-stop-daemon --start --quiet --pidfile \
		    /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	reload)
		echo -n "Reloading $DESC configuration: "
		#test_xwp_config
		start-stop-daemon --stop --signal HUP --quiet --pidfile /var/run/$NAME.pid \
		    --exec $DAEMON || true
		echo "$NAME."
		;;

	configtest|testconfig)
		echo -n "Testing $DESC configuration: "
		if test_xwp_config; then
			echo "$NAME."
		else
			exit $?
		fi
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" xwp && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest}" >&2
		exit 1
		;;
esac

exit 0
